DROP TABLE IF EXISTS USERS;
create table USERS(
	ID number(5) primary key,
	USERNAME varchar2(30),
	PASSWORD varchar2(100),
	EMAIL varchar2(30),
	CREATEDATE TIMESTAMP(26, 6),
	ROLE VARCHAR(255)
)

DROP TABLE IF EXISTS POST;
CREATE TABLE POST(
	ID number(100) primary key,
	CNT number(100) NOT NULL,
	CONTENT CLOB NOT NULL,
	CREATEDATE TIMESTAMP(26, 6),
	TITLE VARCHAR(100) NOT NULL,
	USERID number(100) NOT NULL
)

DROP TABLE IF EXISTS REPLY;
CREATE TABLE REPLY(
	ID number(100) primary key,
	CONTENT CLOB NOT NULL,
	CREATEDATE TIMESTAMP(26, 6),
	POSTID VARCHAR(100) NOT NULL,
	USERID number(100) NOT NULL
)
